// OpenStreetMap extracts in data/; editorial descriptions and unverified venue coordinates.
export const places = [
  {
    "id": "kongens-have",
    "name": "Kongens Have",
    "category": "park",
    "kind": "Park",
    "district": "Indre By",
    "lat": 55.6850892,
    "lng": 12.5798631,
    "osm": "way/118353598",
    "emoji": "🌳",
    "description": "En grön paus mitt i stan. Välj en mötespunkt och ta promenaden därifrån.",
    "meeting": "Vid parkens sydöstra entré, Gothersgade.",
    "accent": "#dae8ca",
    "openingHours": "07:00-17:00; Mar 07:00-19:00; Apr 07:00-21:00; May-Aug 07:00-22:00; Sep 07:00-21:00; Oct 07:00-19:00",
    "outdoor": "unknown",
    "greenSpace": true
  },
  {
    "id": "kayak-bar",
    "name": "Kayak Bar",
    "category": "bar",
    "kind": "Bar vid vattnet",
    "district": "Frederiksholms Kanal",
    "lat": 55.675205,
    "lng": 12.586764,
    "osm": "node/4012815277",
    "emoji": "🍹",
    "description": "Samla vännerna vid kanalen och låt eftermiddagen bli kväll.",
    "meeting": "Vid entrén på Børskaj.",
    "accent": "#d2e9e6",
    "openingHours": "Jun-Aug",
    "outdoor": "yes",
    "greenSpace": false
  },
  {
    "id": "la-banchina",
    "name": "La Banchina",
    "category": "restaurant",
    "kind": "Mat & café",
    "district": "Refshaleøen",
    "lat": 55.6892932,
    "lng": 12.6109061,
    "osm": "node/4430760869",
    "emoji": "🍽️",
    "description": "En träff vid vattnet på Refshaleøen. Kontrollera servering och öppettider före besöket.",
    "meeting": "Vid entrén, Refshalevej 141.",
    "accent": "#d7e4ee",
    "openingHours": "Su-We 08:00-18:00; Th-Sa 08:00-20:00",
    "outdoor": "yes",
    "greenSpace": false
  },
  {
    "id": "orstedsparken",
    "name": "Ørstedsparken",
    "category": "park",
    "kind": "Park & promenad",
    "district": "Indre By",
    "lat": 55.6811139,
    "lng": 12.5665612,
    "osm": "way/3098756",
    "emoji": "🌿",
    "description": "Gångvägar, gröna rum och en lugn stund tillsammans nära stadens puls.",
    "meeting": "Vid entrén på Nørre Voldgade.",
    "accent": "#dce5c8",
    "openingHours": null,
    "outdoor": "unknown",
    "greenSpace": true
  },
  {
    "id": "brus",
    "name": "BRUS",
    "category": "bar",
    "kind": "Bar & restaurang",
    "district": "Nørrebro",
    "lat": 55.6918656,
    "lng": 12.5557824,
    "osm": "node/12798373371",
    "emoji": "🍺",
    "description": "Möt upp på Nørrebro för något i glaset och tid att prata.",
    "meeting": "Vid entrén på Guldbergsgade.",
    "accent": "#eee0d0",
    "openingHours": null,
    "outdoor": "unknown",
    "greenSpace": false
  },
  {
    "id": "host",
    "name": "Høst",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørre Farimagsgade",
    "lat": 55.6832824,
    "lng": 12.5661022,
    "osm": "node/1448422015",
    "emoji": "🍴",
    "description": "Bestäm en middag tillsammans. Uteservering och bordstillgång är inte verifierade.",
    "meeting": "Vid restaurangens entré.",
    "accent": "#e7ded3",
    "openingHours": "17:30-24:00 \"last order 21:30\"",
    "outdoor": "no",
    "greenSpace": false
  },
  {
    "id": "ofelia",
    "name": "Ofelia Plads",
    "category": "park",
    "kind": "Kaj & promenad",
    "district": "Kvæsthusbroen",
    "lat": 55.6816637,
    "lng": 12.595727,
    "osm": "way/529519844",
    "emoji": "🌊",
    "description": "En öppen plats vid hamnen för en träff eller början på en promenad.",
    "meeting": "Vid övergången från Kvæsthusgade till kajen.",
    "accent": "#d6e7ec",
    "openingHours": null,
    "outdoor": "unknown",
    "greenSpace": false
  },
  {
    "id": "osm-24958713",
    "name": "Ølbaren",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6892753,
    "lng": 12.5578754,
    "osm": "node/24958713",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-We 16:00-00:00; Fr 15:00-02:00; Sa 15:00-02:00; Su 16:00-21:00; Th 16:00-01:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-24971137",
    "name": "Juma",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.690348,
    "lng": 12.5640201,
    "osm": "node/24971137",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": null,
    "outdoor": "yes"
  },
  {
    "id": "osm-335962972",
    "name": "Café Stefanshus",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6953457,
    "lng": 12.543356,
    "osm": "node/335962972",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-We 08:00-01:00,Th-Sa 08:00-01:00,Su 11:00-23:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-1118919064",
    "name": "Cafe Runddelen",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6942552,
    "lng": 12.5482944,
    "osm": "node/1118919064",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-Su 12:00-05:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-1775489880",
    "name": "Kung Fu II Izakaya Bar",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.6889266,
    "lng": 12.562565,
    "osm": "node/1775489880",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": "Mo-Sa 17:30+",
    "outdoor": "yes"
  },
  {
    "id": "osm-1830057767",
    "name": "Bindia Elmegade",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.6895902,
    "lng": 12.5582863,
    "osm": "node/1830057767",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": "Mo-Su 16:00-21:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-2229062918",
    "name": "Mikkeller & Friends",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6946446,
    "lng": 12.5432229,
    "osm": "node/2229062918",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-We 15:00-22:00; Th 14:00-23:00; Fr 14:00-01:00; Sa 12:00-01:00; Su 12:00-22:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-3656367927",
    "name": "Klør Dame",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.701174,
    "lng": 12.551194,
    "osm": "node/3656367927",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-Su 09:00-24:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-3659148934",
    "name": "Bæst",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.692219,
    "lng": 12.555909,
    "osm": "node/3659148934",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": "Tu-Su 17:00-22:30",
    "outdoor": "yes"
  },
  {
    "id": "osm-5786719592",
    "name": "Escobar",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6877393,
    "lng": 12.5595897,
    "osm": "node/5786719592",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-Th 16:00-02:00; Fr-Sa 16:00-04:00; Su 16:00-02:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-5873205715",
    "name": "Manifesto Pizza",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.696125,
    "lng": 12.5432144,
    "osm": "node/5873205715",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": "Tu-Th 16:00-22:00; Fr 16:00-24:00; Sa 12:00-24:00; Su 12:00-22:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-6029934580",
    "name": "Skovbar",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.690773,
    "lng": 12.5445454,
    "osm": "node/6029934580",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Tu-Th 16:00-24:00, Fr-Sa 15:00-24:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-6700526583",
    "name": "Hooked",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.6900527,
    "lng": 12.5550218,
    "osm": "node/6700526583",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": "12:00-21:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-7098162233",
    "name": "Klovnens Bodega",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.688681,
    "lng": 12.5440284,
    "osm": "node/7098162233",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Mo-Sa 10:00-01:00, Su 10:00-22:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-7179414878",
    "name": "CC Restaurant",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.6846843,
    "lng": 12.553353,
    "osm": "node/7179414878",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": "Mo-Th 14:00-23:00; Fr-Su 13:00-23:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-8582838546",
    "name": "Silberbauers Bistro",
    "category": "restaurant",
    "kind": "Restaurang",
    "district": "Nørrebro",
    "lat": 55.6932511,
    "lng": 12.5434247,
    "osm": "node/8582838546",
    "emoji": "🍽️",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#d7e4ee",
    "openingHours": null,
    "outdoor": "yes"
  },
  {
    "id": "osm-8706595479",
    "name": "Bar Vivant",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6895249,
    "lng": 12.558191,
    "osm": "node/8706595479",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "Tu-Th 12:00-23:00; Fr, Sa 12:00-24:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-9760524892",
    "name": "Too Old To Die Young",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6887496,
    "lng": 12.5624009,
    "osm": "node/9760524892",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": "12:00-24:00, Fr,Sa 12:00-02:00",
    "outdoor": "yes"
  },
  {
    "id": "osm-12897927507",
    "name": "Under Træet",
    "category": "bar",
    "kind": "Bar",
    "district": "Nørrebro",
    "lat": 55.6878032,
    "lng": 12.5596601,
    "osm": "node/12897927507",
    "emoji": "🍺",
    "description": "Uteservering registrerad i OpenStreetMap. Kontrollera sittplatsen på kartan.",
    "meeting": "Möt upp vid entrén.",
    "accent": "#eee0d0",
    "openingHours": null,
    "outdoor": "yes"
  },
  {
    "id": "osm-park-relation-1443938",
    "name": "Krogebjergparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69623555,
    "lng": 12.4645969,
    "osm": "relation/1443938",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-1782421",
    "name": "Utterslev Mose",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7125727547619,
    "lng": 12.49616675,
    "osm": "relation/1782421",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-18343729",
    "name": "Den Grønne Kile",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.65182325,
    "lng": 12.5466409,
    "osm": "relation/18343729",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-18371033",
    "name": "Rødkildepark",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6988641,
    "lng": 12.509875650000001,
    "osm": "relation/18371033",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-18378308",
    "name": "Lergravsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.662086099999996,
    "lng": 12.619596000000001,
    "osm": "relation/18378308",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-18436149",
    "name": "Karens Minde Aksen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.64606655,
    "lng": 12.528969,
    "osm": "relation/18436149",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-18897697",
    "name": "Kaktus Haven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.663469199999994,
    "lng": 12.560146549999999,
    "osm": "relation/18897697",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-3538243",
    "name": "Superkilen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7026963,
    "lng": 12.543492116666666,
    "osm": "relation/3538243",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-6355063",
    "name": "Kildevældsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.71492525476191,
    "lng": 12.566377852380953,
    "osm": "relation/6355063",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-7532081",
    "name": "Vigerslevparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.646643114285716,
    "lng": 12.49302053095238,
    "osm": "relation/7532081",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-7540831",
    "name": "Vestvolden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68015015,
    "lng": 12.43059177857143,
    "osm": "relation/7540831",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-7748206",
    "name": "Grøndalsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.680233430952384,
    "lng": 12.490608961904762,
    "osm": "relation/7748206",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-8303264",
    "name": "Christianshavns Vold",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.67525752857143,
    "lng": 12.60675313095238,
    "osm": "relation/8303264",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-relation-9792033",
    "name": "Digterlunden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.677240749999996,
    "lng": 12.5326329,
    "osm": "relation/9792033",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-103178151",
    "name": "Marie Christensens Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.693431700000005,
    "lng": 12.49469595,
    "osm": "way/103178151",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-109713051",
    "name": "Rigsarkivets Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6674951,
    "lng": 12.568719999999999,
    "osm": "way/109713051",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-112383102",
    "name": "BaNanna Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70012965,
    "lng": 12.54985035,
    "osm": "way/112383102",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-118310648",
    "name": "Søndermarken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.669157299999995,
    "lng": 12.52410455,
    "osm": "way/118310648",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-118330089",
    "name": "Østre Anlæg",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6903056,
    "lng": 12.580172526190475,
    "osm": "way/118330089",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-118369545",
    "name": "Frederiksberg Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6747031,
    "lng": 12.5254417,
    "osm": "way/118369545",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1186170960",
    "name": "Grønningen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6591605,
    "lng": 12.5868208,
    "osm": "way/1186170960",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-122010372",
    "name": "Hothers Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70176925,
    "lng": 12.5412055,
    "osm": "way/122010372",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-122010380",
    "name": "Mimersparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.704582450000004,
    "lng": 12.54062935,
    "osm": "way/122010380",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-123209272",
    "name": "Rødegårdsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.660899549999996,
    "lng": 12.61141515,
    "osm": "way/123209272",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1234940672",
    "name": "Astrid Lindgrens Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.63759935,
    "lng": 12.58041925,
    "osm": "way/1234940672",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1282840685",
    "name": "Den hemmelige have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68713265,
    "lng": 12.56945935,
    "osm": "way/1282840685",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "24/7",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-131110105",
    "name": "Eidsvoll Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69084435,
    "lng": 12.58770485,
    "osm": "way/131110105",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-131618436",
    "name": "Remiseparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.651775,
    "lng": 12.59630095,
    "osm": "way/131618436",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1322075759",
    "name": "Kammas Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.668151223809524,
    "lng": 12.533258,
    "osm": "way/1322075759",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-133359450",
    "name": "J.C. Jacobsens Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.664334350000004,
    "lng": 12.5333562,
    "osm": "way/133359450",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-133721518",
    "name": "Margethehaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.649814,
    "lng": 12.502479999999998,
    "osm": "way/133721518",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1340009387",
    "name": "Sæterdalsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.656217,
    "lng": 12.6026919,
    "osm": "way/1340009387",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1340043527",
    "name": "Degnemosen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70000175,
    "lng": 12.50528265,
    "osm": "way/1340043527",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1340046702",
    "name": "Bellahøjmarken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.701926400000005,
    "lng": 12.513940049999999,
    "osm": "way/1340046702",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1340055891",
    "name": "Rødkilde Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.697249850000006,
    "lng": 12.5115454,
    "osm": "way/1340055891",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1341475519",
    "name": "Langelinieparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6907827,
    "lng": 12.59924425,
    "osm": "way/1341475519",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1347296929",
    "name": "Den Grønne Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.703071449999996,
    "lng": 12.5437653,
    "osm": "way/1347296929",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1347299136",
    "name": "Glenteparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69766295,
    "lng": 12.53606375,
    "osm": "way/1347299136",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1371647599",
    "name": "Nexus Landscape",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.66311605,
    "lng": 12.558836249999999,
    "osm": "way/1371647599",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1472676613",
    "name": "Betty Nansens Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6702091,
    "lng": 12.50127945,
    "osm": "way/1472676613",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1472680157",
    "name": "Nordens Plads Byrum",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.671936200000005,
    "lng": 12.50266365,
    "osm": "way/1472680157",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-148941761",
    "name": "Aksel Møllers Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.685449750000004,
    "lng": 12.5329588,
    "osm": "way/148941761",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-149092721",
    "name": "Hostrups Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68418355,
    "lng": 12.5394444,
    "osm": "way/149092721",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-149092984",
    "name": "Børge Outzes Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68317305,
    "lng": 12.5415771,
    "osm": "way/149092984",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1507397300",
    "name": "Pioparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6502612,
    "lng": 12.53200675,
    "osm": "way/1507397300",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-151035569",
    "name": "Søfrontparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.67635180952381,
    "lng": 12.555334247619047,
    "osm": "way/151035569",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-152134425",
    "name": "Storbyhaven Valby",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.66681535,
    "lng": 12.512715499999999,
    "osm": "way/152134425",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "24/7",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-152134429",
    "name": "Storbyhaven Valby",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6665349,
    "lng": 12.51217495,
    "osm": "way/152134429",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "24/7",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-153529486",
    "name": "Byhaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69554465,
    "lng": 12.530354849999998,
    "osm": "way/153529486",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-155770924",
    "name": "Amaliehaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6834359,
    "lng": 12.594989349999999,
    "osm": "way/155770924",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-1557943751",
    "name": "Anne Linnets Trekant",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.678874050000005,
    "lng": 12.60348445,
    "osm": "way/1557943751",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-162383253",
    "name": "Valbyparkspejderne",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.64578925,
    "lng": 12.5240452,
    "osm": "way/162383253",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-162597661",
    "name": "Thors Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6965467,
    "lng": 12.54725625,
    "osm": "way/162597661",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-178593819",
    "name": "Søholmslund",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7231703,
    "lng": 12.5560051,
    "osm": "way/178593819",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-218537939",
    "name": "Fælledparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70198325,
    "lng": 12.5685721,
    "osm": "way/218537939",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-22999683",
    "name": "Søborg Mose",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.725272849999996,
    "lng": 12.51945155,
    "osm": "way/22999683",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-23013818",
    "name": "Amager Strandpark - Tiøren",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6485924,
    "lng": 12.64358205,
    "osm": "way/23013818",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-23013819",
    "name": "Amager Strandpark - Femøren",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6468632,
    "lng": 12.64588775,
    "osm": "way/23013819",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-230841013",
    "name": "Poul Henningsens Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7086018,
    "lng": 12.577004899999999,
    "osm": "way/230841013",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-24626894",
    "name": "Lersøparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7096128,
    "lng": 12.54370145,
    "osm": "way/24626894",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25109004",
    "name": "Classens Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.697843649999996,
    "lng": 12.58881585,
    "osm": "way/25109004",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25109231",
    "name": "Julius Thomsens Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.680891450000004,
    "lng": 12.5533632,
    "osm": "way/25109231",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25110138",
    "name": "Landbohøjskolens Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.680178600000005,
    "lng": 12.5418494,
    "osm": "way/25110138",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25148044",
    "name": "Damhusengen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68595725,
    "lng": 12.470032450000001,
    "osm": "way/25148044",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25359360",
    "name": "Bellahøjparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7021713,
    "lng": 12.509376499999998,
    "osm": "way/25359360",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25421990",
    "name": "Skydebanehaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.670552,
    "lng": 12.5537967,
    "osm": "way/25421990",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25422014",
    "name": "Enghaveparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.667152200000004,
    "lng": 12.54215195,
    "osm": "way/25422014",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25451129",
    "name": "Det Kongelige Biblioteks Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.67447315,
    "lng": 12.58137325,
    "osm": "way/25451129",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25451864",
    "name": "Lindevangsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68054625,
    "lng": 12.5114683,
    "osm": "way/25451864",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25452695",
    "name": "Høje Gladsaxe Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7255801,
    "lng": 12.4903166,
    "osm": "way/25452695",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25465934",
    "name": "Hulgårds Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7051273,
    "lng": 12.52220995,
    "osm": "way/25465934",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25478755",
    "name": "Enveloppeparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.66823458809524,
    "lng": 12.592107285714286,
    "osm": "way/25478755",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25674413",
    "name": "Vestvolden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.71674253571429,
    "lng": 12.479236735714286,
    "osm": "way/25674413",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25690811",
    "name": "Grønningen Nordvest",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.71127695,
    "lng": 12.534096850000001,
    "osm": "way/25690811",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25761636",
    "name": "Guldbergs Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6972066,
    "lng": 12.55389925,
    "osm": "way/25761636",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25860301",
    "name": "Ryvangens Naturpark",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7236761,
    "lng": 12.56567199047619,
    "osm": "way/25860301",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-25868187",
    "name": "Kystagerparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.633535440476194,
    "lng": 12.4994945,
    "osm": "way/25868187",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-26088828",
    "name": "Pistolskydebanen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.722553700000006,
    "lng": 12.56389205,
    "osm": "way/26088828",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-26165403",
    "name": "Piosplænen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.64978615,
    "lng": 12.5332638,
    "osm": "way/26165403",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-26315174",
    "name": "Ørestad Bypark",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.63366915,
    "lng": 12.576923950000001,
    "osm": "way/26315174",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-26440246",
    "name": "Hans Tavsens Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6891564,
    "lng": 12.5477865,
    "osm": "way/26440246",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-26489768",
    "name": "Otto Krabbes Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.67018495,
    "lng": 12.5526466,
    "osm": "way/26489768",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-26654635",
    "name": "Churchillparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6885316,
    "lng": 12.595152200000001,
    "osm": "way/26654635",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-27147906",
    "name": "Folkets Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68753945,
    "lng": 12.5546686,
    "osm": "way/27147906",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-27226068",
    "name": "Litauens Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6677018,
    "lng": 12.5522276,
    "osm": "way/27226068",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-27291215",
    "name": "Grønnegården",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.68637415,
    "lng": 12.5935393,
    "osm": "way/27291215",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-27360353",
    "name": "Hjalmar Brantings Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6922828,
    "lng": 12.58154245,
    "osm": "way/27360353",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-295635546",
    "name": "Kastrup Fort",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.64849735,
    "lng": 12.6396363,
    "osm": "way/295635546",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-300557009",
    "name": "Husum Bypark",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7099379,
    "lng": 12.478508399999999,
    "osm": "way/300557009",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-3098803",
    "name": "Botanisk Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6869382,
    "lng": 12.573995199999999,
    "osm": "way/3098803",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "Apr-Sep: 08:30-18:00, Oct-Mar: 08:30-16:00",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-3099108",
    "name": "Hørsholmparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6916502,
    "lng": 12.5427395,
    "osm": "way/3099108",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-3099109",
    "name": "Nørrebroparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69535904999999,
    "lng": 12.54191475,
    "osm": "way/3099109",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-3107466",
    "name": "Filipsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6538933,
    "lng": 12.61761055,
    "osm": "way/3107466",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-312947886",
    "name": "Brønshøjparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70658055,
    "lng": 12.5086725,
    "osm": "way/312947886",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-313263227",
    "name": "Emaljehaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70440755,
    "lng": 12.534378499999999,
    "osm": "way/313263227",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-330777484",
    "name": "Sydpolen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69271775,
    "lng": 12.5574734,
    "osm": "way/330777484",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-330781980",
    "name": "Nordpolen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.69607575,
    "lng": 12.5604041,
    "osm": "way/330781980",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-33508489",
    "name": "Valbyparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.640043250000005,
    "lng": 12.51684565,
    "osm": "way/33508489",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-357147119",
    "name": "Christianshavns Enveloppe",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.674004330952386,
    "lng": 12.608510095238096,
    "osm": "way/357147119",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-404898332",
    "name": "Beboerhusets park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.65237715,
    "lng": 12.60093705,
    "osm": "way/404898332",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-418178029",
    "name": "Trondhjems Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6941791,
    "lng": 12.5884559,
    "osm": "way/418178029",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-419614369",
    "name": "Grønnegården",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.679766900000004,
    "lng": 12.5411486,
    "osm": "way/419614369",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-4250637",
    "name": "Fredens Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6931438,
    "lng": 12.568328300000001,
    "osm": "way/4250637",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "24/7",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-4250656",
    "name": "Amorparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6957048,
    "lng": 12.5645676,
    "osm": "way/4250656",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-425379214",
    "name": "Henrettelsespladsen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.72428735,
    "lng": 12.565493499999999,
    "osm": "way/425379214",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-4347707",
    "name": "Mindelunden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.725890500000006,
    "lng": 12.565932700000001,
    "osm": "way/4347707",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-4349543",
    "name": "Jensen Klints Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7163671,
    "lng": 12.53669785,
    "osm": "way/4349543",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-439211609",
    "name": "Havneparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.66530175,
    "lng": 12.573883200000001,
    "osm": "way/439211609",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-44012523",
    "name": "Kansagerparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7062704,
    "lng": 12.4616933,
    "osm": "way/44012523",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-470756543",
    "name": "Voldparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.714068049999995,
    "lng": 12.4791722,
    "osm": "way/470756543",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-47290268",
    "name": "Sundbyvesterparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6514721,
    "lng": 12.6017756,
    "osm": "way/47290268",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-4766663",
    "name": "Gandhiparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.697834,
    "lng": 12.523573200000001,
    "osm": "way/4766663",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-479438561",
    "name": "Skotlands Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6581231,
    "lng": 12.6048589,
    "osm": "way/479438561",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-480095418",
    "name": "Stærepark",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70256525,
    "lng": 12.5226332,
    "osm": "way/480095418",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-480987209",
    "name": "One tree park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.668054049999995,
    "lng": 12.5498766,
    "osm": "way/480987209",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-486638384",
    "name": "Stjernen Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6896928,
    "lng": 12.533487099999999,
    "osm": "way/486638384",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-48812100",
    "name": "Skovbrynet",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.632477800000004,
    "lng": 12.58201065,
    "osm": "way/48812100",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-507914387",
    "name": "Carl Jacobsens Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6669426,
    "lng": 12.529834099999999,
    "osm": "way/507914387",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "Mo-Fr 16:00-20:00; Sa, Su 10:00-20:00",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-52489318",
    "name": "Nordvestparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70360745,
    "lng": 12.5240519,
    "osm": "way/52489318",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-569034713",
    "name": "Kuglegården",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.678447750000004,
    "lng": 12.6006821,
    "osm": "way/569034713",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-597071144",
    "name": "Odins Lomme",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.696976750000005,
    "lng": 12.550438150000002,
    "osm": "way/597071144",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-617402068",
    "name": "Byfælleden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.62460550238095,
    "lng": 12.571536466666666,
    "osm": "way/617402068",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-639100776",
    "name": "Dyrelegepladsen i Valby",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.64873005,
    "lng": 12.500837,
    "osm": "way/639100776",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-669606998",
    "name": "Blegdamsfælleden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.7009491,
    "lng": 12.5685721,
    "osm": "way/669606998",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-669606999",
    "name": "Klosterfælleden",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.70533265,
    "lng": 12.569284199999998,
    "osm": "way/669606999",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "24/7",
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-692320788",
    "name": "Kulbaneparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.65698245,
    "lng": 12.49298692857143,
    "osm": "way/692320788",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-724268476",
    "name": "Hannemanns Park",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6270297,
    "lng": 12.57877585,
    "osm": "way/724268476",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-794690045",
    "name": "Vesten for Humlen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.667076249999994,
    "lng": 12.53702745,
    "osm": "way/794690045",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-794690046",
    "name": "Østen for Humlen",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6672326,
    "lng": 12.538511100000001,
    "osm": "way/794690046",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-79639378",
    "name": "Pariserhaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.67516435,
    "lng": 12.5413876,
    "osm": "way/79639378",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-810731380",
    "name": "Saxopark",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6707678,
    "lng": 12.5512364,
    "osm": "way/810731380",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-884164846",
    "name": "Grønttorvsparken",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6548052,
    "lng": 12.5046551,
    "osm": "way/884164846",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-88418558",
    "name": "Fremtidsskoven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6732573,
    "lng": 12.601128,
    "osm": "way/88418558",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-89696804",
    "name": "Glyptotekshaven",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.67212009285714,
    "lng": 12.571472521428571,
    "osm": "way/89696804",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-91712721",
    "name": "Højsager Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.660901800000005,
    "lng": 12.48384055,
    "osm": "way/91712721",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-943317190",
    "name": "Kofoeds Plads",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.666094799999996,
    "lng": 12.6182629,
    "osm": "way/943317190",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": null,
    "outdoor": "yes",
    "greenSpace": true
  },
  {
    "id": "osm-park-way-956136408",
    "name": "Bodil Kochs Have",
    "category": "park",
    "kind": "Park",
    "district": "Köpenhamn med omnejd",
    "lat": 55.6808688,
    "lng": 12.5327486,
    "osm": "way/956136408",
    "emoji": "🌳",
    "description": "Park registrerad i OpenStreetMap. Utforska grönskan och välj en mötespunkt tillsammans.",
    "meeting": "Bestäm en mötespunkt i parken tillsammans.",
    "openingHours": "24/7",
    "outdoor": "yes",
    "greenSpace": true
  }
];
export const activityFor = category => ({park:'walk',bar:'bar',restaurant:'restaurant'})[category];
export const activityNames = {walk:'Ta en promenad',bar:'Gå till en bar',restaurant:'Ät tillsammans'};
